<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-Q8UQAUDS" ignored="6" name="Default test(failed)" tests="1" failures="1" timestamp="2022-07-29T22:08:37 IST" time="0.16" errors="0">
  <testcase name="test3" time="0.026" classname="testNG.Sample11">
    <failure type="java.lang.AssertionError" message="Test 3 is fail">
      <![CDATA[java.lang.AssertionError: Test 3 is fail
at testNG.Sample11.test3(Sample11.java:28)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test7" time="0.0" classname="testNG.Sample11">
    <ignored/>
  </testcase> <!-- test7 -->
  <testcase name="test6" time="0.0" classname="testNG.Sample11">
    <ignored/>
  </testcase> <!-- test6 -->
  <testcase name="test5" time="0.0" classname="testNG.Sample11">
    <ignored/>
  </testcase> <!-- test5 -->
  <testcase name="test2" time="0.0" classname="testNG.Sample11">
    <ignored/>
  </testcase> <!-- test2 -->
  <testcase name="test4" time="0.0" classname="testNG.Sample11">
    <ignored/>
  </testcase> <!-- test4 -->
  <testcase name="test1" time="0.0" classname="testNG.Sample11">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
